export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL="GET_PRODUCT_FAIL"


export const ADD_NEW_PRODUCT_REQUEST="ADD_NEW_PRODUCT_REQUEST"
export const ADD_NEW_PRODUCT_SUCCESS="ADD_NEW_PRODUCT_SUCCESS"
export const ADD_NEW_PRODUCT_FAIL="ADD_NEW_PRODUCT_FAIL"


export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL"